version: 1.2
workflows:
  - name: cnvkit-end-to-end
    subclass: WDL
    primaryDescriptorPath: /CnvKit.wdl
    
  - name: cnvkit-coverage
    subclass: WDL
    primaryDescriptorPath: /modular/CnvKitCoverage.wdl